### Задание 1

In [2]:
import numpy as np

In [3]:
col1 = [1, 2, 3, 3, 1]
col2 = [6, 8, 11, 10, 7]


In [4]:
a = np.stack((col1,col2),axis = 1)

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = a.mean(0)

In [7]:
mean_a

array([2. , 8.4])

### Задание 2

In [8]:
a_centered = a-mean_a

In [9]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [10]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]

In [11]:
N = a.shape[0]
a_centered_sp /= N-1
a_centered_sp

2.0

### Задание 4

In [12]:
m = np.transpose(a)
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [13]:
np.cov(m)[0,1]

2.0